version: "3.3"
services:
  webapp:
    build: .
    ports:
      - "80:5000"
    restart: always
    image: run
    environment:
      - FLASK_SECRET_KEY="${FLASK_SECRET_KEY}"
      - CONNECTION_STRING="${CONNECTION_STRING}"
